name: Test the thing
on:
  push:
    branches:
      - '!master'
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install npm dependencies
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: install
    - name: Lint Dockerfile
      uses: docker://cdssnc/docker-lint
    - name: Run JS linter
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: run lint

