name: Test, build, and push
on: push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install npm dependencies
        run: npm install
      - name: Lint Dockerfile
        uses: docker://cdssnc/docker-lint
      - name: Run JS linter
        run: npm run lint
  deploy:
    name: Build container and push
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@master
      - name: Build the Docker image
        run: docker build --tag base --build-arg GITHUB_SHA_ARG=${{ github.sha }} .
      - name: Tag :latest
        run: docker tag base cdssnc/next-holidays:latest
      - name: Tag :$GITHUB_SHA
        run: docker tag base cdssnc/next-holidays:${{ github.sha }}
      - name: Login into Docker Hub
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Push container to Docker Hub
        run: docker push cdssnc/next-holidays
